# Generated by Django 3.2 on 2022-03-11 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'verbose_name_plural': 'Urls'},
        ),
        migrations.AddField(
            model_name='urls',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urls',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
