# Generated by Django 3.2 on 2022-03-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0002_auto_20220311_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
