# Generated by Django 3.2 on 2022-03-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortner', '0003_auto_20220311_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='updated_date',
            field=models.DateField(auto_now=True),
        ),
    ]
